#Порт приложения
server:
  port: 8083
#Логгирование
logging:
  level:
    org.springframework.ws: TRACE
#Конфиг для подключения проекта к админке
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin
        instance:
          metadata:
            user: user
          name: active-mq-service
  #Логин пароль для доступа
  security:
    user:
      name: user
      password: user
#Для актуатора
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#Ссылка на брокера, распределяющая сообщения
activemq:
  broker-url: tcp://localhost:61616